---
repos:
  # Formatters
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        exclude: .*valid.*
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
  - repo: local
    hooks:
      # run `terraform fmt` if tf files are modified and terraform is installed
      # when terraform is not installed, this check will succeed even if tf files
      # would not pass the format check
      - id: terraform-fmt
        name: terraform-fmt
        entry: bash -c 'if command -v terraform >/dev/null 2>&1; then terraform
          fmt -recursive -check terraform; else exit 0; fi'
        language: system
        types:
          - terraform
        pass_filenames: false

ci:
  autofix_prs: true
