import { DataProvider } from "@/utils/DataContext"
import "./global.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <DataProvider>
        <body>{children}</body>
      </DataProvider>
    </html>
  )
}
