import "./global.scss"
import Header from "./header"
import Footer from "./footer"
import { DataProvider } from "@/utils/DataContext"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="grid-container main-body">
         <DataProvider>
           {children}
         </DataProvider>
        </div>
        <Footer />
        </body>
    </html>
  )
}
