import "./global.scss"
import Header from "./header"
import Footer from "./footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="grid-container maxw-desktop-lg main-body">
          {children}
        </div>
        <Footer />
        </body>
    </html>
  )
}
