config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "${env:MY_POD_IP}:4317"
        http:
          endpoint: "${env:MY_POD_IP}:4318"
  processors:
    batch: {}
  exporters:
    logging:
      loglevel: "debug"
  extensions:
    health_check:
      endpoint: "${env:MY_POD_IP}:13133"
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging]
      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [logging]
