name: End-to-end test

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment in which to conduct end to end testing."
        type: string
        required: true

permissions:
  id-token: write
  contents: read
  packages: write
jobs:
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Check Out Changes
        uses: actions/checkout@v3
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - name: Azure defaults
        env:
          LOCATION: ${{ secrets.LOCATION }}
          RESOURCE_GROUP_NAME: ${{ secrets.RESOURCE_GROUP_NAME }}
        run: az config set defaults.location=$LOCATION defaults.group=$RESOURCE_GROUP_NAME