---
name: Test
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
