---
name: Test
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  lint-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./front-end
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run linter
        run: npm run lint
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./front-end

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm install

    - name: Run Jest Tests
      run: npm run test
